### ISSUE TITLE
cross_evaluate immediately hanging

### ISSUE THREAD

**Issue by StevenGin** [hsahovic/poke-env#162] opened 2021-05-22 09:43 UTC
Working my way through the examples, however on the cross_evaluate example, running the code immedaitely hangs after printing this.

`2021-05-22 02:40:40,484 - Player 1 - WARNING - Received pm: |pm| Player 1| Player 2|/challenge gen7randombattle|gen7randombattle|||
2021-05-22 02:40:40,485 - Player 2 - WARNING - Received pm: |pm| Player 1| Player 2|/challenge gen7randombattle|gen7randombattle|||
2021-05-22 02:40:40,485 - Player 1 - WARNING - Received pm: |pm| Player 1| Player 2|/text Player 1 wants to battle!
2021-05-22 02:40:40,485 - Player 2 - WARNING - Received pm: |pm| Player 1| Player 2|/text Player 1 wants to battle!`

**Comment by hsahovic** [comment] 2021-05-22 23:16
Hey @StevenGin,

Thanks for bringing this up. I believe this was caused by [this PR](https://github.com/smogon/pokemon-showdown/pull/8303) in `pokemon-showdown`, which changed the way challenges are processed. I am working on implementing it into `poke-env`, and will release it before the end of the weekend.

**Comment by hsahovic** [comment] 2021-05-23 00:59
This is solved by #163 and released in `poke-env` 0.4.14. Please upgrade the version you are using (`pip install --upgrade poke-env`) or pull master (`git pull master` in your `poke-env` clone) :)

**Closed by hsahovic** 2021-05-23 00:59 UTC
Labels: bug
